name: 'Telegram'
description: 'Process and persist latest bookmarks from Telegram'

inputs:
  data-path:
    description: 'Path of the data in JSON format'
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.data-path }}
